### PR TITLE
Gradle update

### PR DESCRIPTION
**Pull request by simon-andrews**
Remember to install the Gradle Eclipse plugin: https://github.com/spring-projects/eclipse-integration-gradle#installing-gradle-tooling-from-update-site

Set `client/src/main/java`, `common/src/main/java` and `server/src/main/java` to be source folders (Right click project > properties > Java Build Path > Source).

### CODE REVIEW

**Comment by Math-ias** [comment]
I would really prefer if you made SocketWrapper a common resource
**EDIT**: K

**Comment by simon-andrews** [comment]
Let's put that off for now. First I need to figure out how to make common something that the other two repositories can depend on with Gradle's dependency system.

**Comment by simon-andrews** [comment]
SocketWrapper is be a common resource now.

**Comment by Math-ias** [comment]
Building is not too slow (I rate it _meh_) the first build I did took 6.474 seconds roughly and the second (without changing code) took 4.214 seconds.

**Comment by simon-andrews** [comment]
Try enabling the [Gradle daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html).

**Comment by jakekinsella** [comment]
Gradle daemon is still meh. Especially because it does not always run in the background (it shuts off after  3ish hours, I think) and when it shuts off you start to get 6 second deploys again until it starts back up.

**Comment by simon-andrews** [comment]
Can you guys both give me what Gradle version you are using?

**Comment by jakekinsella** [comment]
2.3

**Comment by simon-andrews** [comment]
It should be noted that Gradle isn't the only option for building now. If you're just in Eclipse making changes to one project and you want to see what those changes do you can still run your code as a Java Application and bypass Gradle entirely.

**Comment by jakekinsella** [comment]
+1 (Assuming you are ready)

**Comment by simon-andrews** [comment]
@Math-ias ?

**Comment by Math-ias** [comment]
+1

**Pull request merged**
