### PR TITLE
Main server code

### PR DESCRIPTION
**Pull request by Math-ias**
**NOTE**: I have yet to test the gradle build.

### CODE REVIEW

**Comment by Math-ias** [comment]
The gradle build fails. :frowning:

**Comment by jakekinsella** [comment]
Erm... I hope you know how to rebase...

**Comment by jakekinsella** [comment]
And to the gradle comment: http://soundbible.com/581-Police-Siren-3.html Call Simon!

**Comment by Math-ias** [comment]
I don't need to rebase, I did a test merge, worked fine. It just looks like there are a million new commits.

**Comment by jakekinsella** [comment]
Also just a heads up, we use "_" for spaces instead of "-" in branch names

**Comment by Math-ias** [comment]
But I don't want to! Too much energy!

**Comment by simon-andrews** [comment]
> Also just a heads up, we use "_" for spaces instead of "-" in branch names

Since when? Also, it [goes against convention](http://stackoverflow.com/a/24223634/4541644) and it's ugly.

**Comment by simon-andrews** [comment]
> The gradle build fails. :frowning:

What's the error?

**Comment by jakekinsella** [comment]
Simon just to tell you there is no "official" convention for naming branches.

**Comment by simon-andrews** [comment]
Why did you put "official" in quotes? I didn't say that. If you read the link I provided you would see that it links to two commits to Git itself that show that there is a preference in the Git developer community towards dash as a separator. Dashes also fit in with the way Git does things. Git uses dashes instead of underscore everywhere.

Also, you didn't address "Since when?"

**Comment by jakekinsella** [comment]
Obviously the topic of branch naming needs to be addressed in our next meeting because we all have conflicting ideas on how branches should be named. Let's suspend this conversation until Tuesday.

**Comment by simon-andrews** [comment]
It doesn't need to be addressed because it's a non-issue. The code standards got it right already:

> Branch names are a controversy. No comment, do what you want as long as you use correct spelling, write a name that describes a functionality and use a consistent naming scheme.

**Comment by jakekinsella** [comment]
As I said before, lets suspend this conversation until Tuesday and stop using Mahias's branch as a place for conversations.

**Comment by Math-ias** [comment]
Fixed the gradle stuff, it builds now!

**Comment by Math-ias** [comment]
Dangit.

**Pull request closed without merging**
