### PR TITLE
Move MainView's action listener to MainView itself

### PR DESCRIPTION
**Pull request by jakekinsella**
Also when a button is pressed it disables itself and enables the other one

### CODE REVIEW

**Comment by jakekinsella** [comment]
Mathias took too long...

**Comment by Math-ias** [comment]
Haha, yeah, I was moving to another operating system these past few days.

**Comment by Math-ias** [comment]
I haven't looked too hard to see if my presumptions are correct but I think that the onEnableButtonPress() method and the like can be private since they won't be used outside the class, am I right?

**Comment by jakekinsella** [comment]
They are used outside of the class (MainView calls Controller.main.onEnableButtonPress())

**Comment by jakekinsella** [comment]
@Math-ias

**Comment by Math-ias** [comment]
+1 I guess

**Pull request merged**
